---
apiVersion: v1
kind: Namespace
metadata:
  name: web-app-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: web-app-namespace
  name: app-server
  labels:
    app: app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-server
  template:
    metadata:
      labels:
        app: app-server
    spec:
      containers:
        - name: app-server
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/appserver:075a473
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: APP_ENV
              value: "dev"
---
apiVersion: v1
kind: Service
metadata:
  namespace: web-app-namespace
  name: app-server-service
spec:
  type: ClusterIP
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-app-to-app-server
  namespace: web-app-namespace
spec:
  podSelector:
    matchLabels:
      app: app-server
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: web-app
      ports:
        - protocol: TCP
          port: 8080
  policyTypes:
    - Ingress
