apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/backend:8abcabf
          ports:
            - containerPort: 5500
          env:
            - name: FLASK_ENV
              value: development
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: default
spec:
  encryptedData:
    DB_HOST: AgBmix8qM2FHicLJXHX+1NquvVfxhDCR6gODsIaMW49b+xKPHdM56yxIFIWqLFlEg/TkQ+hRD6NST+1eZeaTrbMKfN2bl3ITAlN5boBgePNmMPS7xmwyTVF0IatCBp3k6Go7/718tRx4A6FSw/DApm497/vTgWvVUyF/AIg2x9PGhsJpi5jJ6xeiuRz3Bok1SzKhK67PWgaGTiHUaVQ1t5dNSwQH4VJkXt+WCsTEeS0/3xKfYFn3up+vTadEN83qwSEYrFIUS+XnkZbZRw9whmDgP20vAxAN3M1T5gb893iKWqL+KaZUGSCVKzQgLtop3byX+ujTIo2DiRxlmnK3thIvahGtG3l8oTeGYJXLm7aY8jq2S6+zAgFuRMX83NbCr2gUpKD5+aljimmaTQnu2BXixFRImQRxTPD9lf2RntTHOSYdkDQuka5hipmCMVftwAgLHDygHs6hS3YKX4y5Vfz0q0XpY+IdhLfdDsXaYP+OOOEZckB7EVWkJaC0qxE6zy84yTYXze4sSaznp1wSrUvNpVoGBAb89j7JCfWPINCXiqvZXvbpCRjqHJKVE+0ySnG3sSuZymkp43SphnwU8sXvL49iBX95sT40PwGxo3gsx6n/Yr1YuIF9z0EyCIv+zXxbFCWa0Imxt5O1QuFQUf4Grn5U5KqC+iytIWoP13+cBPq6rEUlc4wz8SrBxKsf/o5MWV4cDH+GUuU=
    DB_NAME: AgAPtzKe0wsZwxjMPWG/ddO0dKqu2CijhvfD7Nzhiaj/nzEsHHSTAEGI/vS3cmUASbYS/ZN35UHWamx0A9jJNOdlDkfXDK+bWkY4tcbHMCzrun7C/CegekUaVhwI4FHld/KLjOfF5Zx1FRb6W4JRs1HRDNcFdcnd4c0+QHuO9ERF75mY9V208E1zVxp2FUZ4cWpSQI7J6IzBrXgqngKhR4248x1ERCdvp51GEkTYNEGISn267iF86lWomi0YAAIi2RfZzSB3o7wodcAooQOu46621lcL8QAEaXlXfR9pJNqMj8A5CshuTStEAwzWAC/8jsObJIjFEAyMFgieDSRNKJNc9FzW66tBL+tUrj4tlCkDo5KDsTwfXNvvvXm2aVTiFOjS9IFRHpo6ft6WyLU+vTryyqav4RkMLkNUBf8MGtFT1wdzQByOlWW+Xets3GyU0tSMe9Sk0Zu6WV7rzDiy5dhpRwff6t8XnRpkDk921W3XgcgW6OP0999NtN054O+IyOUYEP+9dorpFPNy9KkVNcAqcZW3jn2fPKX3AMKuJepu+FLztOGJ5zOgI/GSDY2tasQokdLACDUm5cdcZZyS8eIDnfE4AYu2Stcd9qe4oJgYJwhQ2ERXuOP9NLjEFI/ZL6BfTdxU+R6wqZBjT1J4XrHvUrvz95RZf7qe51SnYjF767K9hCVCWgn995bW2Hc420eznDx5dH6pWA==
    DB_PASSWORD: AgCsmZiN2+wC3H6TVEW9MiG1gmC426pN8l6AMy+d2cZsWXxlVN6gAbB/33xdr46UaxXWhHYPbWlCfuiH+6/4tqwiEYQ47xeq2CV4zSzuq14NsuatiNVvzFYxGjkmso1oHPPqtskuiI5SxYdNJzYVUSc2KX7ycYQo4CdClBxT8eVUIj1rmQTakeu8o9cMh1uSOHXWHG/n6qOXbNx1Nm48KctQXEKywu16meNPmyGdBbfOpjPBuNsv1NrJ1oUeNJdu+ZdBmFO+2wDPj/mPnJMyX1XkBWBpikxAHrU6ZMZ4X7GbojHKP3Na2wb2AjmOUkLEX3GtwXhHwbFSLQ2G8mllJst1uC7BHhrP0Od96idHoXP6AEdQi91Djjb5kHEa04Fu0eYM+/wizOZZTJiNYf5p4SVvnMw5ISL6yttXdvPvzXjCIHflSnzYabhp39X6Kc8KtASJaMCvtqr884mIlPUhMrrhRrtrgQywiZMffLLBHDblHWobanxDdUD7rgS+uXHlj89ayD/ceWVYmJTlJDrWvF/LQ8sc7iGO/0xMCKIaZVvBrmJ5l00iELczM69PV3ZYsKdf1LqWcNxGlb7zvevilG8GW7aN98lWS+YByDVLLdESpaM1GkpJrynBJn43EzAi8OnfQK4+qpOYerIWuxB1yietdgHbEsg84zzVialvbTsND8C2YQ8V4M1KfqOq0kQYOLIQHK4PpKLItzs=
    DB_USER: AgByA9eTNHmUnw/drn1bNZCsqrh31mlogXFzFe4v5BQEwjXkGs/l5fE0zrBtBEa2JQ+STFZ4CljQPHaWD0NCS4FxZpGtyyeAWP/oEotky3LRoBx7U8n3isw6wckrAIZLc1CCJZLuuiLh0TBzVAenVfToDUy+TLQbNtv4wH4sKTgOI8O/aKpjMMkCoWmjJKysTMdKCXZCWUF4JlJIByKtCfjNtMJRPh1NDUrWxyWs8vXaWohrdXS3vM/J22Uxrno//NvFPnpoFYuUm0w4A8a939fKWRwUjo6EkJLE048mtkSHEvY3JofjAll3HonWqa90QvpioFPlW77SJB4k0g9EI3FRnhWjdJKWEXQERsS5586rS8WtRLsThufGANGB4XpSQSIcEplRcmvWV2yBrXUTW7KBNYwO6zbfw1WqkPG0NCqUSCzmDpaZDKDrdVYsy8m5zTFywx+fm+NkcALEibDwNaEvR4wVabBhd3YNJepXXuIb+J8xkqFPr/0wi6MoxtsZtMl87zsUIxtX6xTPxs2ntSgC8bS9ouC1/U2Z0Ta411accgnj9t2r5J6E6bUw+PAvi2xNrNRxpgZ8MP+Gj10aTRprvERa2w8OuM3bN3DPHWBvj/E43PGVXGx3W06x78tHN7cJeuYJgQyBps7AQY+3+b1QJwrj0rxqyUez7p5H1V7teosyoj7eBxrYYwlUh5x5RSiLIvYUiw==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: default
    type: Opaque
