apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/backend:8ab474f
          ports:
            - containerPort: 5500
          env:
            - name: FLASK_ENV
              value: development
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: default
spec:
  encryptedData:
    DB_HOST: AgBL/hlxojIfE3K8ZQ/MHzMltDoFxn203ICVacDA4u676aLbdNHSYjrq8drhBQ5WVa2rFaErSAK+Vrul88yYOeN/xUyGUxXxbByWWHmzXtBYqLdwX90S9KFE6ndtM6GyVfpqD5bBshBQIkRzGHNoVM62hV9zmzJ8L4vy8dXKNAsOMLnutuVSyYVZj7eO55gM8xbss1CPCWBgXgrIWTfEux6fJnYRcE6eOvBCmBmNNKKL7ER23Vr+x/zsHCiuGvIyxXMy/pZFl54mI2ZlyFOOMYbLTZNaGViqbwMfRKBGPUSwbQ17Uk/JXeTueBEUjqf0NxydS+TSkOXPOzzUyQIS2Ww1q6pegBOrgSdKzfe+REvXF+eDZGaktt8rjxpj2FeSoBm2ASaeuQlhwwR8p5LSmMwWWjdPFeWXo+sVRx+PYmVj5NpFnubg/A6maoHIXj62D/zOTFfaTwhr3oSGnoTJSWc6yUxWgn9eVhqrayENBIfweCkcIZqU0QVmFu5kSEeIcAf1wz0PD1kiwNdymE/+t+riZroR3XP1tcHIf4nJdcpPXqiLbzPjKDJmFYUd/yzHqg7mHha4p8qlvTurRGPnfIvk1qiUcx36QUeXL5Xs5R0moWPjK/a4CvHeixPq1P98qZFfUdl+TE7bEj9FuWCyohmdaPM5V8Bbas893cTU8uxEUTACeORUIaF/tEsBWycbhNLDsFNhXqRtb7Q=
    DB_NAME: AgBsiw3bnFRTYdBRsk7/K9vpxwMtP1PM8vaE0QdY2qgX4NeNfcnSZAU6M54aKcwSpzndo0Jok4T1OF9hjt9Thjq948tYfUxuE1pExuhlMZNjfi890RxtNDlkAf2aTAkxPi3jmH4+RN/RrZVS2m5o53WEBqi64Ot5Umnetfv82PDwK8zJ275ao8MdTUe7wZqLkNDBEcMAeVsfxdbbcheqxxxsqXNRmGARPnaPwDoy58sga6jtNgLFzlZtA8qy9ETpuGfnk7Sc0Z9xGrx0KbMwiq9qN3CFOA6mPCURpr66qHfPopV89rBRkxizwQWctM3mB2IC1edFGbjkhxGpiJ+N8B5GJkRtFBvAYTJLEyQZsIWGZMLudRI+x142dZ56LgqKNuFQ5ybWnCfJXC4VOOqBdU6zYxtksAG1pYKMAGxvF79mZu8eUZpT98offQRDcwMw9mnyyqdvx0TGVLOr0wYeJfUYz61pvJE2WDyEnew9XPsY5Zc6IDmti7o0EOD67BKmWhGAgGTobmo2awfwjj9QC/GIR5xWGo2+oBoTSamWomkH6HLnuJJJYcj5l3oS8UPE7+YXkQt8nGr9ltmfhcCRwbZFrSh6BDSpRGpbkGxVv5kNQh7uH/k/OL/1UkIMxtMkFUzy8lJlAmqWMt8eAD8+bWjQw3v7fyf4lnB0HDZiSafDWGUgvY+wLBdCPOIlTSWLcLyMXj11s8DBXw==
    DB_PASSWORD: AgBy2C/bORD67IMw9tuSiGVsDdq5N7/3ullvULpbYXH4/5R8k4BfSj/MvOYEuB839l/jPlQFNha8GErA98mjSFSjEPnJxqWye0im0kvZYfUry2daGlMYl9APKcIiRczwiwG1KG/+4XTElaWw/KgKNZK1Oy/K8YK9gHSp1wBR8GLaLhASQSM+FJCMlrqCAaLWlhmQuXdZE0fBkj9gzz4o8pte/ryEJIWpceoHvoma5IED5IaZmGceQKeKgTJYiB9ZTCPUZWYiFnHcp4JQwyLxIsRESYzIIODFFCjPrYnSPS3uASFU1i7XYwYjXqFY0dkObe2nmlCM2h3CvpWwEFehV7xtvUaQuKT/EJaq0nyLrI6AaEwHqUDH7WO68KEkM8sKJks6jmNiHBDzW7bMwsPT2roVvDkPB5yMzQGMURBgIziBfXiwnuIFKpYKwV8iZS/mUkJkQt72ddQVhWfeSXA4aWFp5QYt3QQGETVgS0pTBemZ78Y0mg/Ahvb3cqRRx/WLHARXOXPdnkXU8IFt3i/ChsP/ZeB7aEOFibxUg5lWXoCa+Kpm2B1PCriXIABxzji+ACZpMCMqnXKAZnDkwfvMh0cN5BMAsWuEEuTnVPQZ3sTTVSe2CFNquNLNWQJoj6MfAN3nrT+l4Re3oAgSLq58+73/wLCSjPAr2C7I4FgTkM67m9Q57X6chGJcLrD+0zb3exoFeVe9JfXour0=
    DB_USER: AgBnwlZiAyjOcG+jwuX0On2rstQs7GzON50GinGwSj3dii6Wq3mynJfg0GwSctU8GXVAO0S/KdUAhMQAQ/RCimugGIR/3zhK/Zbh45TKCdS7S4lWVEUBhTyteYPSjT5HGeiSQDm6+bubXgq/CiKpzi6n05rZ7Bs4BHpIqYmhGn+eloiCZq9g+laIc65VKTA9Vbpk7uvb8rGZISOk8VfHzVVgA/K825NKZn2YzcaiC553wYK0tRYB4DOblcDJRUqhFQB3+ZBI+IYYmcXBpjNE3PeqXk32WUsZgBKDl0plHAwrGqYG89IMbmZDu69edtJtUUvJ3E4aaYCW+a//tDLA1I0xQroLei5/D399n7qll1MbN7XeVAxIvT93gshykErqeZnvVLNU3kJg3SQOG/YCTyZso4SWoxIRnRugZMXgeZ++JqKQrY3e3lqc9E8u1OXmdqxEjN/qsa1pZNUsx/NcAwlL5++ht/u9G4Lb5qPDJtdR5Rx3dpjT0yyY6GPG0H3SIoXJnwYnFZuBOIRWZVtgeIQR4Lz1i5WNygKWQ1kP+l39G4mHOeejEzeniIEHR48gEgNdtWrqwUBcdKSz4tQvEa1Z3bKlsU6SWVl83oT+XR+rniJ3+TsEsy5AttYCOJy5K0vqMS93bPBQGQyoqECb4oMHFeHoHWJVo27FDZncSm8lpm6Qg33SOfZIooFyDiFs+kBHvEYTew==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: default
    type: Opaque
    
