apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/backend:9eb6b3b
          ports:
            - containerPort: 5500
          env:
            - name: FLASK_ENV
              value: development
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: DB_PASSWORD
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: default
spec:
  encryptedData:
    DB_HOST: AgBbIYinnrfPnoGfctJJDQEdctRayVHUHLUOkPzbXBFklKA67BKOF3x8XNjzfdUxczSpDBuFGCUrqubkYR3wMBJvcykLljg0x1g1XnXfR32ep2ok35P9WzEVAcckA2j6Szm9guV93KcG/bvLuJTr2hCe5pPHsFPkfN2minZNALg1caLshxmF03d1Vi5bTlQiCMs+39rk4pjw+MWOPhg9beMwybPMzLjk8W5G4ESfDWKXEjV7B0OEEkgSxtgJMrS98aECgQoYBF7PCJAUmdVzKnTcIWy/GoykIbTfvw8x/mDULnxYqClWcXHN/AC8abyogvoJnC/IQGDKTCWNvqWS+qQNrcuel1aE2DhJfcRAEauQjgNcbhCyhXEmNPNAHNKyEfxCOdTLzYtF+LPsKx2aArm+KYlFVzjiSvMcmGwA7sKjckvHakpkgJsFpFrI0hckdp5FjZFVHNReVik0EBI8YbnjIiqdaHmlZmXbCOuTwJv99WyhkKMOxif7Fh+aCOMqqtpuK91bM3GjpZEga+Bk2lYcNfjWJzpqrxcd2Lbu/jYnABPiEeBcch5cbcebLaqCwWK7H27U3C0P36FImiSb9DamNLQo6tX8+PLzODtT8wYtcp3w6eii7lqiw36AWydHnPtcE1Ytt71LDsfMDWB2B2nqvhU19aj/x5r8NJP0MPXNYoKcEGXGzVcBVUGPXnPOSQQoIuxqDdlX1Ak=
    DB_NAME: AgCumG9FxB6C10w6AQzXn9hReExECsPfOQxmPFwD9yBtB3i5rVfwFmFN7AjIBHWUlBmu324548+ipCsbwkQmCPXEeWpWZDz2u4d8Rnf+tPNaPI/kI8y8THkfPT+2fnFGWLtZNPyBXSr+OLKdfU/6abJORVlkTmvde1eFZ43RmXm3QL6MOigik+uTPrthBRZQVn2UzbvfiUHZxGvXCe7Itf1w8XCAZaAlCYEwGejXXaJrcozr9KLfg9+qWzv1zgZYT4o1P//0s+F4rZk5Q2GvqqZMrP2myNOdiOzLlDEEBo3H+KmM5RUyjiSny/1NtVcM01+62+c1i22ccRzBTGYfe1TmqUWPT6mruZaO2Tj3fPAtBHIUnfRI+OsvV4Xy1eJ9Npft7CnId7CSHZWYfdl8epA4vaIOghKHIoa936QgyO+djlzASomeKqr6kzD3nJS0NwZiMj4JE0nFMMTwg2kazTcIPvo7nkaK8TLQqMh0PYyH47b1hFyJOsdgqhs944Y2dv30gpBKFdjn6NNvyNlsfpJZ8X7+jHKi/JT78BsxXFwZ9NgPaKPSzjdZHP9DCaca/LcFCwIj54qulup+yBu6olrtyQ80rCyv7b81F2nEiUpn1Tl55vuvRXf3Jfa2cli8BhvpoW8n2V8nL/SGvmCCFpvMqvz/H6jbsI/MkY+6VWAhOilL+b56EKf5QcZakyvKpoe3MOz6CDYiYw==
    DB_PASSWORD: AgAVl7+BPXSxZwyS3ZZLSqtFbVUGvCWCkMzev+RnGWapqZovOdQPjaf4/IHShbKdOnjQa3EAcodCx4Z4h8RrE9P7oqpZVJx9XFT1cotw2Q5jYp3sGonOd2h569b3Lggzea0Hpid2kH65+QjXky0pmLGM3h5WSJIa3NNK+vhiGE3hDFu4l4Eh+cTiBVO80E1WCcZgp4ppSzttd7nzzOQXEU9SZfRpdWcqtY7Sf9rn8enM4uXm+mYre73pUI+B+FZmjRk6nWqCZ1tdAPbZFHMneQOAdj3KrQhW1i3yFI/tK059wJasXGDo0ZA3mbMfIGz7FYNoVh2f/q0W+qZkIH/gf+5EEWzUP4gjUkM0fS1jlrHyKdvm+ZfH+0PpHFetk2fiiBRTYCVsFZD2B6Ps8Kt3hWhMcEdGdSF/dtUguG3b46VJuBcmwtwFpS/7foyeuhkJjUe9y9NdH1twX502hKbW4ZLG5gANFPpyczRuRkPNJJh8YHoqrSuwkPb7c0TQZiwpR9Oqu3Y7vXuILoy8878Rx424Li5wR0KqJnWl6WXNeonY9jNWBEIpXMFfsnJKfZAfp57xOqIfDeKntOVSw24xO3MPyz7PFFRHcRv7XKn4XXYKwrnZ0agifsznUvKfykNbbu7FCqys1V5gRCQnic5+SxoS1gMHTRGiwTCrqa6KKOe9m4VSjkADUNLmJDU+eyyY3bAgWRLxiou73gE=
    DB_USER: AgAK7jKk8RDdI0+0D1KxpdioCZ/dwpq1fUubup9NoxbUmq1pgrQLd8JoJRpZKurAjsca7z2FfZYYax3A1SdYMYh/xozCnSjtysRAuygyh6U52BHSEB9SD2rrxNmSYJUmXPHFtvNJEx+9GJIO/zUB3eDTXYENoo3wFoE998W85DjAgnTa00YR2Cw9SVJQe+aWiEza8GXn3nrzfUt7eBXnKTB1ypGfj2fhEYl+YLyloXeYHG7Mm5P9Tm4f6NDmh/4iaUGaoDcD5o0vQp2ImNw0+VjWfPgI4Claer2WMruOItqZH4xLZf6Z9D9PIwFZ52i+6Mn5bIs6tbPXYigVvvYo0yq+gCVG0wmUQbd9pq9eve/KglyttnI5u/2OMTcu1ODbBHwquAlr0IRFytTgUd4iHfJa37pbYMVM7u/hwcsQyUeVy04nkoiEp8l18xsFrTdfjfaY2sqPLlkTEYzdYgjA1LfNWrnlOBMvnlj+yUXve+Db9FVOT5Pis15jKPOJuyyG77zZfs3eahcqEjyjIDc9XPABSPFgZ5S9OnJhbfguVZOyVwxrCzFIP5ty5QW3RYxDVdiW0ORTBpI/rLXiHZUla9bwHpbfzcgTY6FwDt/EHGjVEcuDBydY+cMNRoBaOwWzrMU79sgh8yFl7ry6Rxk1r6FZzbP7Dapz9Xh5mBvfDhTOtZPzGv6Okzuvs/wzQwjdWUtH9EAynA==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: default
    type: Opaque
