apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/backend:cb1e638
          ports:
            - containerPort: 5500
          env:
            - name: FLASK_ENV
              value: development
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: backend
