---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 5001
      targetPort: 5001
  selector:
    app: frontend
  type: LoadBalancer
