apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: canary
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/backend:12481f6
          ports:
            - containerPort: 5500
          env:
            - name: FLASK_ENV
              value: development
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
            requests:
              memory: "64Mi"
              cpu: "25m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: canary
spec:
  ports:
    - port: 5500
      targetPort: 5500
  selector:
    app: backend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: canary
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
