---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-stable
  labels:
    app: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary
      version: stable
  template:
    metadata:
      labels:
        app: canary
        version: stable
    spec:
      containers:
        - name: frontend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:b6eaf9c
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
  labels:
    app: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary
      version: canary
  template:
    metadata:
      labels:
        app: canary
        version: canary
    spec:
      containers:
        - name: frontend
          image: 571515939637.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:v1.0.0
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  ports:
    - port: 5002
      targetPort: 5001
  selector:
    app: canary
  type: LoadBalancer
