name: CI/CD pipelines
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
    
    paths-ignore:
      - 'argocd/**'
      - 'manifest/**'
      - 'README.md'

permissions:
  id-token: write
  contents: read
jobs:
  EKS-deploy:
    name: Provision EKS infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571515939637:role/infra_assessment
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          cd infra/EKS
          terraform init -var-file "variables-dev.tfvars" -backend-config "key=eks.tfstate"

      - name: Terraform Plan
        id: plan
        run: |
          cd infra/EKS
          terraform plan -var-file "variables-dev.tfvars" -out=tfplan

      - name: Terraform Apply
        id: apply
        run: |
          cd infra/EKS
          terraform apply tfplan

  ECR-deploy:
    name: Provision ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571515939637:role/infra_assessment
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          cd infra/ECR
          terraform init -var-file "variables-dev.tfvars" -backend-config "key=ecr.tfstate"

      - name: Terraform Plan
        id: plan
        run: |
          cd infra/ECR
          terraform plan -var-file "variables-dev.tfvars" -out=tfplan

      - name: Terraform Apply
        id: apply
        run: |
          cd infra/ECR
          terraform apply tfplan

      # ## Get terraform output and update to env-vars
      # - name: Get ECR URL
      #   id: ecr
      #   run: |
      #     cd infra/ECR
      #     terraform output -json > ecr.json
      #     echo "ECR_URL=$(jq -r '.ecr_url.value' ecr.json)" >> $GITHUB_ENV
      #     echo "ECR_REPOSITORY=$(jq -r '.ecr_repository.value' ecr.json)" >> $GITHUB_ENV

  build:
    needs: [EKS-deploy, ECR-deploy]
    name: Build and push Docker image
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571515939637:role/infra_assessment
          aws-region: ap-southeast-1

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install -r src/frontend/requirements.txt
          pip install -r src/backend/requirements.txt

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ap-southeast-1

      - name: Set short git commit SHA and github tag to make decision whether build is for release or not
        id: vars
        run: |
          echo "::set-output name=sha::$(git rev-parse --short=7 ${{ github.sha }})"
          
      - name: Print env vars
        run: |
          echo "github.ref='${{ github.ref }}'"
          echo "github.event.base_ref='${{ github.event.base_ref }}'"
  
      - name: Prepare Docker Tags
        id: docker-tags
        run: |
          COMMIT_SHA=${{ steps.vars.outputs.sha }}
          echo "COMMIT_SHA_TAG=$COMMIT_SHA" >> $GITHUB_ENV
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF/refs\/tags\//}
            echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
            TAGS="$VERSION_TAG,$COMMIT_SHA"
          else
            TAGS="$COMMIT_SHA"
          fi
          echo "DOCKER_IMAGE_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build frontend image
        id: build-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
        run: |
          # Build Docker image
          cd src/frontend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY -f Dockerfile .
          
      - name: Push frontend to Amazon ECR
        id: push-frontend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: frontend
        run: |
          # Push Docker image to Amazon ECR
          IFS=',' read -ra TAGS <<< "$DOCKER_IMAGE_TAGS"
          for TAG in "${TAGS[@]}"; do
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          done

      - name: Build backend image
        id: build-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
        run: |
          # Build Docker image
          cd src/backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY -f Dockerfile .
        
      - name: Push backend to Amazon ECR
        id: push-backend-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
        run: |
          # Push Docker image to Amazon ECR
          IFS=',' read -ra TAGS <<< "$DOCKER_IMAGE_TAGS"
          for TAG in "${TAGS[@]}"; do
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG
          done

  update-web-app-deployment:
    name: Bump image versions
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Deployment Image
        env:
          ECR_REGISTRY: ${{ needs.build.outputs.ecr_registry }}
          IMAGE_TAG: ${{ needs.build.outputs.sha }}
        run: |
          git pull --rebase origin main
          IMAGE_TAG=${{ needs.build.outputs.sha }}
          sed -i 's|image: '${{ env.ECR_REGISTRY }}/backend':.*|image: '${{ env.ECR_REGISTRY }}/backend':'"$IMAGE_TAG"'|' manifest/backend.yaml
          sed -i 's|image: '${{ env.ECR_REGISTRY }}/frontend':.*|image: '${{ env.ECR_REGISTRY }}/frontend':'"$IMAGE_TAG"'|' manifest/frontend.yaml
          git add *
          git commit -m "Update image versions to $IMAGE_TAG"
          git push -u origin main