name: Destroy infrastructure
on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  eks-detroy:
    name: Destroy EKS infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571515939637:role/infra_assessment
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          cd infra/EKS
          terraform init -var-file "variables-dev.tfvars" -backend-config "key=eks.tfstate"

      - name: Terraform Destroy
        id: destroy
        run: |
          cd infra/EKS
          terraform destroy -var-file "variables-dev.tfvars" -auto-approve

  ecr-detroy:
    name: Destroy ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::571515939637:role/infra_assessment
          aws-region: ap-southeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: |
          cd infra/ECR
          terraform init -var-file "variables-dev.tfvars" -backend-config "key=ecr.tfstate"

      - name: Terraform Destroy
        id: destroy
        run: |
          cd infra/ECR
          terraform destroy -var-file "variables-dev.tfvars" -auto-approve
  